wandb_version: 1

transformations:
  desc: null
  value: true
paths:
  desc: null
  value:
    dataset_download_path: /ssd_scratch/cvit/varun/
    model_save_path: /ssd_scratch/cvit/varun/vit_ti_hard_dist_no_token
dataset:
  desc: null
  value: cifar
val_split:
  desc: null
  value: 0.04
batch_size:
  desc: null
  value: 2048
transormer_config:
  desc: null
  value:
    use_default_vit_B: false
    use_default_vit_S: false
    use_default_vit_Ti: true
    custom_config:
      img_size: 32
      in_chans: 3
      patch_size: 16
      embed_dim: 768
      depth: 12
      n_heads: 12
      qkv_bias: true
      mlp_ratio: 4
optimizer:
  desc: null
  value: adam
model_name:
  desc: null
  value: vit_ti_hard_dist_no_token
distillation_type:
  desc: null
  value: hard
teacher_model_path:
  desc: null
  value: /ssd_scratch/cvit/varun/regnet_y_16gf_32_3
training_epochs:
  desc: null
  value: 100
initial_lr:
  desc: null
  value: 0.0003
wandb:
  desc: null
  value:
    enable: true
    project_name: DeIT
    run_name: vit_ti_HardDistillationNoToken_regnet16gf_pretrained
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683291020.387886
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.2
      5: 0.14.2
      8:
      - 5
