transformations: True
paths:
    dataset_download_path: /ssd_scratch/cvit/varun/
    model_save_path : /ssd_scratch/cvit/varun/vit_s_hard_dist_no_token

dataset : cifar #cifar / imagenet32
val_split : 0.04
batch_size : 2048

transormer_config:
    use_default_vit_B: False
    use_default_vit_S: True
    use_default_vit_Ti: False
    custom_config:
        {
        img_size: 32,
        in_chans: 3,
        patch_size: 16,
        embed_dim: 768,
        depth: 12,
        n_heads: 12,
        qkv_bias: True,
        mlp_ratio: 4}


optimizer : adam #sgd / sgd_m / sgd_l2 / rms
model_name : vit_s_hard_dist_no_token
distillation_type : hard #soft
teacher_model_path: /ssd_scratch/cvit/varun/regnet_y_16gf_32_3
training_epochs: 100
initial_lr : 0.0003

wandb :
    enable: True
    project_name : DeIT
    run_name : vit_s_HardDistillationNoToken_regnet16gf_pretrained

