dataset_path: /ssd_scratch/cvit/varun/dataset
valid_ratio: 0.04
custom_config : {
        img_size: 32,
        in_chans: 3,
        patch_size: 16,
        embed_dim: 768,
        depth: 12,
        n_heads: 12,
        qkv_bias: true,
        mlp_ratio: 4 
        }

train_batch_size: 2048
valid_batch_size: 2048
save_model_path: /ssd_scratch/cvit/varun/VIT_models/
save_model_name: VIT_base_no_resize
config_write_path : /ssd_scratch/cvit/varun/VIT_models/
learning_rate: 3e-4
epochs: 1000
wandb_project : DeIT
wandb_run_name: vit_base_model_scratch_no_resize