transformations: True
paths:
    dataset_download_path: /ssd_scratch/cvit/varun/
    model_save_path : /ssd_scratch/cvit/varun/trained_models

dataset : cifar #cifar / imagenet32
val_split : 0.04
train_batch : 512

transormer_config:
    use_default_vit_B: True
    use_default_vit_S: False
    use_default_vit_Ti: False
    custom_config:
        {
        img_size: 32,
        in_chans: 3,
        patch_size: 16,
        embed_dim: 768,
        depth: 12,
        n_heads: 12,
        qkv_bias: True,
        mlp_ratio: 4}


optimizer : adam #sgd / sgd_m / sgd_l2 / rms
model_name : vit_b_reg16gf_hard_dist
distillation_type : hard #soft
student_model : vitb #vitb / vits / vitti / vitbD / vitsD / vittiD
teacher_model_path: /ssd_scratch/cvit/varun/regnet_y_16gf_32_3
training_epochs: 100
initial_lr : 3e-4

wandb :
    enable: False
    project_name : DeIT
    run_name : vitb_HardDistillation_regnet16gf_pretrained"

