paths:
    dataset_download_path: /ssd_scratch/cvit/shaon/cifar-100-python
    model_path : /ssd_scratch/cvit/shaon/vit_b_reg16gf_hard_dist_19

dataset : cifar #cifar / imagenet32
batch_size : 1024
num_workers : 4

transformer_config:
    use_default_vit_B: True
    use_default_vit_S: False
    use_default_vit_Ti: False


model_type : Transformer #cnn

mode : Normal #distilled_token 

